# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cloudkeeper.proto for package 'cloudkeeper.grpc'

require 'grpc'
# require 'cloudkeeper_pb'

module Cloudkeeper
  module Grpc
    module Communicator
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'cloudkeeper.grpc.Communicator'

        rpc :PreAction, Google::Protobuf::Empty, Status
        rpc :PostAction, Google::Protobuf::Empty, Status
        rpc :Migrate, Google::Protobuf::Empty, Status
        rpc :AddAppliance, Appliance, Status
        rpc :UpdateAppliance, Appliance, Status
        rpc :RemoveAppliance, Appliance, Status
        rpc :RemoveImageList, ImageListIdentifier, Status
        rpc :ImageLists, Google::Protobuf::Empty, stream(ImageListIdentifier)
        rpc :Appliances, ImageListIdentifier, stream(Appliance)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
